name: build

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build container
        run: docker build -f Containerfile . -t fedora

      - name: Extract RootFS
        run: |
          docker create --name fedora fedora echo "Fedora Linux"
          docker export -o rootfs.$(dpkg --print-architecture).tar fedora
          gzip rootfs.$(dpkg --print-architecture).tar
          docker rm fedora

      - name: Generate vars
        id: vars
        run: |
          echo "arch=$(dpkg --print-architecture)" >> "$GITHUB_OUTPUT"

      - name: Upload RootFS
        uses: actions/upload-artifact@v4
        with:
          name: rootfs.${{ steps.vars.outputs.arch }}
          path: rootfs.*.tar.gz

  release:
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download RootFS
        id: download-rootfs
        uses: actions/download-artifact@v4
        with:
          path: rootfs
          pattern: rootfs.*
          merge-multiple: true

      - name: List artifacts
        run: ls -R ${{ steps.download-rootfs.outputs.download-path }}

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${tag#v}" \
            --generate-notes \
            ${{ steps.download-rootfs.outputs.download-path }}/*.tar.gz
